import 'dart:convert';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
// Used to receive push notifications from Firebase.
// Gets messages sent from server
// Gives you message.title, message.body, message.data
import 'package:app_settings/app_settings.dart';
// 👉 Used to open phone settings automatically.
// Opens notification settings
// Used when user denies permission
// Think: “Take user to settings screen”
import 'package:flutter/material.dart';
// Basic Flutter UI library.
// Buttons, screens, navigation, context
// Almost every Flutter app needs this
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
// Used to show notification popups manually.
// Needed when app is OPEN
//think like: “Show notification on screen”
import 'package:get/get.dart';
// 👉 Used for snackbars, navigation, state management.
// Here you’re using it for:
// Showing error messages (Get.snackbar)
// Think: “Easy alerts & navigation”
import 'dart:io';
// Used to check which platform the app is running on.
// Android?
// iOS?
import 'package:flutter/foundation.dart';
// import 'package:lost_and_found/ui/screens/detailscreen.dart';
// 👉 Used for debugging.
// kDebugMode → prints only in debug mode
// import 'package:lost_and_found/ui/screens/homepagescreen.dart';

// import 'package:lost_and_found/ui/screens/myclaimscreen.dart';

// import '../ui/screens/chat_room_screen.dart';
// import '../ui/screens/ownerclaimscreen.dart';
// import 'package:your_app/screens/main_screen.dart'; // 👈 Add the correct import for MainScreen

class NotificationService {
  FirebaseMessaging messaging = FirebaseMessaging.instance; //It receives messages from Firebase servers.

  final FlutterLocalNotificationsPlugin _flutterLocalNotificationPlugin = FlutterLocalNotificationsPlugin();
  // This shows notification popups on the phone screen
  // (especially when app is OPEN)
  // 💡 Important:
  // Firebase delivers the message
  // Local Notifications displays it

  // Asking Notification Permission
  void requestNotificationPermission() async {
    NotificationSettings settings = await messaging.requestPermission(
      alert: true, //show popup notifications
      announcement: true, //Siri can read it (iOS)
      badge: true, //show number on app icon
      carPlay: true, //show in car screen (iOS)
      criticalAlert: true, //allow urgent alerts
      provisional: true, //allow silent notifications first (iOS)
      sound: true, //play sound
    );

    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      // User said YES
      // 👉 Notifications are fully allowed
      print('User granted permission');
    } else if (settings.authorizationStatus == AuthorizationStatus.provisional) {
      // User didn’t say a full yes, but allowed:
      // Notifications silently
      // No popup, no sound
      print('User provisional granted permission');
    } else {
      // User denied notification permission
      // So you do two things:
      Get.snackbar(
        "Notification permission denied",
        "Please allow Notification to recieve updates.",
        // Shows a small message to explain
        // “Notifications are off. Please enable them.”
        snackPosition: SnackPosition.BOTTOM,
      );
      // Open app notification settings
      // After 2 seconds, the app
      // Opens the phone’s notification settings
      // User can manually turn notifications ON
      Future.delayed(const Duration(seconds: 2), () {
        AppSettings.openAppSettings(type: AppSettingsType.notification);
      });
    }
  }

  // Get device token
  Future<String> getDeviceToken() async {
    // WHAT IS THIS TOKEN?
    // 👉 This token is the address of the phone.
    // “Which phone should receive the notification?”
    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );
    //ust like before, the app asks the user for permission.
    // Here it asks only for basic permissions: alerts, badges, sound.
    // You cannot send notifications without permission, so this step is required.

    // Getting the token
    String? token = await messaging.getToken();

    // Here’s what happens under the hood:
    // FirebaseMessaging.instance → your Flutter plugin object for messaging.
    // .getToken() → asks the FCM SDK on the device:
    // “What’s the unique token for this app instance on this phone?”
    // FCM SDK checks:
    // Did it already generate a token? → return it
    // Not yet? → generate a new one, save it internally on the device, and return it
    // The token is then present in Flutter as a string.

    // Device token is generated by FCM SDK on the device.
    // Flutter plugin exposes it via getToken()
    // Token is just a string representing this app instance.
    //..... You must send it to your server to receive targeted notifications.
    print("✅Token => $token");

    return token!;
  }

  // init
  // This function is all about setting up local notifications on the device,
  // so the app can show a notification popup when a Firebase message arrives
  void initLocalNotification(
      BuildContext context, RemoteMessage message) async {
    // context → Flutter context, needed for navigation if user taps the notification.
    // message → the Firebase message object, containing title, body, and data.
    var androidInitSetting = const AndroidInitializationSettings(
      '@mipmap/ic_launcher',
    );
    //AndroidInitializationSettings tells Flutter which icon to use for notifications on Android.
    // @mipmap/ic_launcher → the default app icon
    // You can use your custom icon if you want.
    // ✅ Simple meaning:
    // “On Android, show this icon in the notification.”

    var iosInitSetting = const DarwinInitializationSettings();
    // It sets up iOS notifications defaults (sound, badge, alert).
    // ✅ Simple meaning:
    // “On iOS, use default notification behavior.”

    var initializationSetting = InitializationSettings(
      android: androidInitSetting,
      iOS: iosInitSetting,
    );
    // FlutterLocalNotificationsPlugin requires a single object containing both Android & iOS settings.
    //
    // This InitializationSettings object is what we pass to the plugin.
    // ✅ Simple meaning:
    // “Here’s how notifications should look on Android and iOS.”

    await _flutterLocalNotificationPlugin.initialize(
      initializationSetting,
      onDidReceiveNotificationResponse: (payload) {
        handleMessage(context, message);
      },
    );
    //   This line actually sets up local notifications on the device.
    // onDidReceiveNotificationResponse → what happens when user taps the notification:
    // Here, you call handleMessage(context, message)
    // This means: open the correct screen when the notification is tapped.
    // ✅ Simple meaning:
    // “Set up notifications and define what happens if user taps it.”
  }

  // firebase init
  void firebaseInit(BuildContext context) {
    // Takes context because we may need it to navigate to a screen when notification is tapped.

    //when app is runnign in foreground..
    FirebaseMessaging.onMessage.listen((message) {
      // FirebaseMessaging.onMessage → fires whenever a notification arrives while the app is in the foreground (open).
      // message contains:
      // title → notification title
      // body → notification body
      // data → extra info like chat ID
      // ✅ Simple meaning:
      // “Whenever a notification comes while app is open, run this code.”
      RemoteNotification? notification = message.notification;
      // notification → the main notification (title, body)
      AndroidNotification? android = message.notification?.android;
      // android → Android-specific info (like channel ID, importance)
      // Simple meaning:
      // “Get the info from the message so we can show it.”

      if (kDebugMode) {
        print("notification title: ${notification?.title}");
        print("notification body: ${notification?.body}");
      }
      //ios
      if (Platform.isIOS) {
        iosForegroundMessage();
      }
      // On iOS, notifications don’t automatically appear if the app is open.
      // iosForegroundMessage() tells iOS: “Show alert, badge, and play sound even if app is open.
      // ✅ Simple meaning:
      // “For iOS, make sure user sees the notification even if app is open.”


      //android
      if (Platform.isAndroid) {
        initLocalNotification(context, message);
        //handleMessage(context, message);
        showNotification(message);
        //   Android also doesn’t automatically display notifications exactly how you want.
        // initLocalNotification(context, message) → sets up notification appearance
        // showNotification(message) → actually shows the popup on screen
      }
    });
  }



  // This section is about how notifications are shown and handled in your app — both when the app is open, in background, or terminated.

  //function to show notifications
  Future<void> showNotification(RemoteMessage message) async {
    // This function actually displays a notification popup on the phone.

    AndroidNotificationChannel channel = AndroidNotificationChannel(
      message.notification!.android!.channelId.toString(),
      message.notification!.android!.channelId.toString(),
      importance: Importance.high,
      showBadge: true,
      playSound: true,

      //   Creates a notification channel for Android (required on Android 8+).
      // importance: high → makes sure the notification pops up visibly and makes sound.
      // showBadge: true → shows a number on app icon.
      // playSound: true → plays notification sound.

      // 🔔 Why do we need to create a Notification Channel
      // On Android 8.0 (API 26) and above, Android will NOT show any notification unless it belongs to a notification channel.
      //  👉 If you don’t create a channel → notification may not appear
      //   🧠 What is a Notification Channel?
      // Think of a channel as a category for notifications.
      // Example categories:
      // Chat messages
      // Order updates
      // Promotions
      // Alerts
      // Each channel has its own settings like:
      // Sound
      // Vibration
      // Importance (high / low)
      // Badge
      // Users can control these from phone settings.

      // ✔ Firebase message contains a channel ID
      // ✔ You create the same channel locally
      // ✔ Android matches them
      // ✔ Then Android shows notification correctly

    );
    //android setting
    AndroidNotificationDetails androidNotificationDetails =
    AndroidNotificationDetails(
      channel.id.toString(),
      channel.name.toString(),
      channelDescription: "Channel Description",
      importance: Importance.high,
      priority: Priority.high,
      playSound: true,
      sound: channel.sound,
      //   Detailed Android settings for the notification.
      // Controls: priority, sound, badge, channel, etc.
    );
    //ios setting
    DarwinNotificationDetails darwinNotificationDetails =
    const DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
      //   iOS notification settings.
      // presentAlert: true → show popup
      // presentBadge: true → show number on app icon
      // presentSound: true → play sound
    );
    //merge setting
    NotificationDetails notificationDetails = NotificationDetails(
      android: androidNotificationDetails,
      iOS: darwinNotificationDetails,
      //   Combines Android + iOS settings into one object for Flutter to use.
    );
    //show notfication
    Future.delayed(Duration.zero, () { //"Run this right after Flutter finishes what it’s doing now."

      _flutterLocalNotificationPlugin.show(
        0,
        message.notification!.title.toString(),
        message.notification!.body.toString(),
        notificationDetails,
        payload: "my_data",
        //   this actually shows the notification popup on screen.
        // title → notification title
        // body → notification body
        // payload → extra data (can be used when user taps notification)
        // ✅ Simple summary:
        // This function shows the notification exactly how you want it on Android and iOS.



        //   payload is extra hidden data attached to the notification.
        // It is mainly used when:
        // 👉 User taps the notification
        // 👉 Your app opens
        // 👉 You can read this payload and decide what screen to open

        //   ✅ Example use
        // payload: "open_chat"
        // Later:
        // onDidReceiveNotificationResponse: (response) {
        //   print(response.payload);   // open_chat
        // }
        // So you can do:
        // if (response.payload == "open_chat") {
        //    // Navigate to Chat Screen
        // }


      );
    });
  }

  //background and terminated
  // This function handles when the user taps a notification while the app is backgrounded or terminated.
  Future<void> setupInteractMessage(BuildContext context) async {
    // background state
    FirebaseMessaging.onMessageOpenedApp.listen(
      // Background state: app is open but in background.
      // Triggered when user taps a notification.
      // Calls handleMessage() to navigate to the right screen.
          (message) {
        handleMessage(context, message);
      },
    );

    // terminated state
    FirebaseMessaging.instance.getInitialMessage().then(
      // Was the app opened by tapping a notification when the app was CLOSED?
      // If yes → it gets that notification → then runs your function.
          (RemoteMessage? message) {
        if (message != null && message.data.isNotEmpty) {
          handleMessage(context, message);
          //   This ensures tapping a notification opens the correct screen whether app is backgrounded or fully closed.

        }
      },
    );
  }

  // handle message
  //
  // //new
  // // This function navigates to a specific screen based on the message data.
  // Future<void> handleMessage(
  //     BuildContext context,
  //     RemoteMessage message,
  //     ) async {
  //
  //   final chatId = message.data['chatId'];
  //   final otherUid = message.data['otherUid'];
  //
  //   if (chatId != null && otherUid != null) {
  //     Navigator.push(
  //       context,
  //       MaterialPageRoute(
  //         builder: (context) => ChatRoomScreen(
  //           chatId: chatId,
  //           otherUid: otherUid,
  //         //   Gets chat info from message.data.
  //           // Opens ChatRoomScreen with the correct chatId and otherUid.
  //         ),
  //       ),
  //     );
  //   }
  // }
  Future<void> handleMessage(
      BuildContext context,
      RemoteMessage message,
      ) async {

    final screen = message.data['screen'];

    if (screen == "chat_room") {
      final chatId = message.data['chatId'];
      final otherUid = message.data['otherUid'];

      // Navigator.push(
      //   context,
        // MaterialPageRoute(
        //   builder: (_) => ChatRoomScreen(
        //     chatId: chatId,
        //     otherUid: otherUid,
        //   ),
        // ),
      // );
    }
    else if (screen == "my_claims") {
      // final chatId = message.data['chatId'];
      // final otherUid = message.data['otherUid'];

      // Navigator.push(
      //   context,
      //   MaterialPageRoute(
      //     builder: (_) => MyClaimsScreen(
      //       // chatId: chatId,
      //       // otherUid: otherUid,
      //     ),
      //   ),
      // );
    }

    else if (screen == "OwnerClaimsScreen") {
      // Navigator.push(
      //   context,
      //   // MaterialPageRoute(
      //   //   builder: (_) => const OwnerClaimsScreen(),
      //   // ),
      // );
    }
    else if (screen == "itemDetail") {
      final itemId = message.data['itemId'];

      final doc = await FirebaseFirestore.instance
          .collection("items")
          .doc(itemId)
          .get();

      final item = doc.data()!;

      // Navigator.push(
      //   context,
      //   MaterialPageRoute(
      //     builder: (_) => ItemDetailScreen(itemId: itemId),
      //   ),
      // );
      // Navigator.push(
      //   context,
      //   // MaterialPageRoute(
      //   //   builder: (_) => ItemDetailScreen(item: item),
      //   // ),
      // );
    }
  }

  // iOS message
  Future iosForegroundMessage() async {
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
    //   On iOS, notifications don’t automatically appear when the app is open.
    // This tells iOS:
    // Show popup (alert)
    // Show badge
    // Play sound
    // ✅ Simple summary:
    // Ensures iOS shows notifications even when app is open.
  }
}