// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3GtNFepz9IqbTnK8bAcklXpqs_zeSKYY',
    appId: '1:790518871168:web:0a6afbdbe3c67a10fde265',
    messagingSenderId: '790518871168',
    projectId: 'lost-and-found-634f2',
    authDomain: 'lost-and-found-634f2.firebaseapp.com',
    storageBucket: 'lost-and-found-634f2.firebasestorage.app',
    measurementId: 'G-K9QQ8PX6S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChTNGEVH5RIdelzv3Ab5ekjDQWdngBvvs',
    appId: '1:790518871168:android:0cdb047740887ad3fde265',
    messagingSenderId: '790518871168',
    projectId: 'lost-and-found-634f2',
    storageBucket: 'lost-and-found-634f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0p0pAH1kGFp16VWVZYhCy8RorE4kQxDE',
    appId: '1:790518871168:ios:ae665890e9a3e1cafde265',
    messagingSenderId: '790518871168',
    projectId: 'lost-and-found-634f2',
    storageBucket: 'lost-and-found-634f2.firebasestorage.app',
    iosBundleId: 'com.example.adminpanellostandfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0p0pAH1kGFp16VWVZYhCy8RorE4kQxDE',
    appId: '1:790518871168:ios:ae665890e9a3e1cafde265',
    messagingSenderId: '790518871168',
    projectId: 'lost-and-found-634f2',
    storageBucket: 'lost-and-found-634f2.firebasestorage.app',
    iosBundleId: 'com.example.adminpanellostandfound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3GtNFepz9IqbTnK8bAcklXpqs_zeSKYY',
    appId: '1:790518871168:web:7057ef1f9b4474d0fde265',
    messagingSenderId: '790518871168',
    projectId: 'lost-and-found-634f2',
    authDomain: 'lost-and-found-634f2.firebaseapp.com',
    storageBucket: 'lost-and-found-634f2.firebasestorage.app',
    measurementId: 'G-52FEQLV7W9',
  );
}
